import type { Metadata } from "next";
import "./globals.css";
import "sweetalert2/dist/sweetalert2.min.css";
import { AuthProvider } from "@/context/AuthContext";
import ScrollToTop from "./components/ScrollToTop";
import Navbar from "@/components/Navbar";
import ThemeBridge from "@/components/ThemeBridge";
import FloatingChatButton from "@/components/FloatingChatButton";
import MobileBottomNav from "@/components/MobileBottomNav";
import AskEpicAiOverlay from "@/components/AskEpicAiOverlay";
import GlobalErrorToastBridge from "@/components/GlobalErrorToastBridge";

export const metadata: Metadata = {
  title: "Epic Show",
  description: "Generated by create next app",
};

const themeInitScript = `
(() => {
  try {
    let mode = "light";
    const raw = localStorage.getItem("user-theme-preferences-v1");
    if (raw) {
      const parsed = JSON.parse(raw);
      const userThemes = parsed?.state?.userThemes || {};
      mode = userThemes.guest || Object.values(userThemes)[0] || mode;
    }
    if (mode !== "dark" && mode !== "light") mode = "light";
    const html = document.documentElement;
    html.classList.remove("theme-light", "theme-dark", "light", "dark");
    html.classList.add(mode === "dark" ? "theme-dark" : "theme-light");
    html.classList.add(mode === "dark" ? "dark" : "light");
    html.style.colorScheme = mode;
  } catch {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body
        className="antialiased"
      >
        <AuthProvider>
          <GlobalErrorToastBridge />
          <ThemeBridge />
          {/* <SmoothScroll> */}
          <Navbar />
          {/* <FloatingChatButton /> */}
          <MobileBottomNav />
          <ScrollToTop />
          {children}
          <AskEpicAiOverlay />
          {/* </SmoothScroll> */}
        </AuthProvider>
      </body>
    </html>
  );
}
